# Generated by Django 3.2.6 on 2021-08-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210822_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_request_at',
            new_name='last_request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
    ]
