# Generated by Django 3.2.6 on 2021-08-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
